server:
  port: 8080

spring:
  application:
    name: currency-service

  datasource:
    url: jdbc:h2:mem:currencies_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      settings.trace: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog/changelog-master.xml